namespace DiskInfoToolkit.Enums.Interop
{
    public enum VendorIDs : ushort
    {
        HDDGeneral = 0,
        SSDGeneral = 1,
        SSDVendorMtron = 2,
        SSDVendorIndilinx = 3,
        SSDVendorJMicron = 4,
        SSDVendorIntel = 5,
        SSDVendorSamsung = 6,
        SSDVendorSandforce = 7,
        SSDVendorMicron = 8,
        SSDVendorOcz = 9,
        SSDVendorSeagate = 10,
        SSDVendorWdc = 11,
        SSDVendorPlextor = 12,
        SSDVendorSandisk = 13,
        SSDVendorOczVector = 14,
        SSDVendorToshiba = 15,
        SSDVendorCorsair = 16,
        SSDVendorKingston = 17,
        SSDVendorMicronMU03 = 18,
        SSDVendorNVME = 19,
        SSDVendorRealtek = 20,
        SSDVendorSkhynix = 21,
        SSDVendorKioxia = 22,
        SSDVendorSSSTC = 23,
        SSDVendorIntelDC = 24,
        SSDVendorAPACER = 25,
        SSDVendorSiliconMotion = 26,
        SSDVendorPhison = 27,
        SSDVendorMarvell = 28,
        SSDVendorMaxiotek = 29,
        SSDVendorYMTC = 30,
        SSDVendorSCY = 31,

        SSDVendorJMicron60X = 32,
        SSDVendorJMicron61X = 33,
        SSDVendorJMicron66X = 34,
        SSDVendorSeagateIronWolf = 35,
        SSDVendorSeagateBarraCuda = 36,
        SSDVendorSandiskGB = 37,
        SSDVendorKingstonSUV = 38,
        SSDVendorKingstonKC600 = 39,
        SSDVendorKingstonDC500 = 40,
        SSDVendorKingstonSA400 = 41,

        SSDVendorRecadata = 42,

        SSDVendorSandiskDell = 43,
        SSDVendorSandiskHP = 44,
        SSDVendorSandiskHPVenus = 45,
        SSDVendorSandiskLenovo = 46,
        SSDVendorSandiskLenovoHelenVenus = 47,
        SSDVendorSandiskCloud = 48,

        SSDVendorSiliconMotionCVC = 49,
        SSDVendorAdataIndustrial = 50,

        SSDVendorMax = 99,

        VENDOR_UNKNOWN = 0x0000,
        USB_VENDOR_BUFFALO = 0x0411,
        USB_VENDOR_IO_DATA = 0x04BB,
        USB_VENDOR_LOGITEC = 0x0789,
        USB_VENDOR_INITIO = 0x13FD,
        USB_VENDOR_SUNPLUS = 0x04FC,
        USB_VENDOR_JMICRON = 0x152D,
        USB_VENDOR_CYPRESS = 0x04B4,
        USB_VENDOR_OXFORD = 0x0928,
        USB_VENDOR_PROLIFIC = 0x067B,
        USB_VENDOR_REALTEK = 0x0BDA,
        USB_VENDOR_GENESYS = 0x05E3,
        USB_VENDOR_ALL = 0xFFFF,
    }
}
